### ISSUE TITLE
Replace LidoRelayer with BalancerRelayer

### ISSUE THREAD

**Issue by markusbkoch** [balancer/frontend-v2#2281]
With every upgrade to the Balancer Relayer we add new features to it and keep the old ones. It should be possible to replace the LidoRelayer, used to wrap/unwrap stETH, with the latest version of the BalancerRelayer (the same we used for pool migration).

**Comment by slumericanB** [comment]
> With every upgrade to the Balancer Relayer we add new features to it and keep the old ones. It should be possible to replace the LidoRelayer, used to wrap/unwrap stETH, with the latest version of the BalancerRelayer (the same we used for pool migration).

**Comment by mikemcdonald** [comment]
I'll get this updated pending discussions around if the `typechain` package is planning to be supported going forward
