### ISSUE TITLE
Stake LP token allows input token amount

### ISSUE THREAD

**Issue by khbw** [balancer/frontend-v2#2846]
**Is your feature request related to a problem? Please describe.**
Now the UI cannot enter the amount of locked LPs, it must be locked all at once. 

**Describe the solution you'd like**
I think it would be better if the user can enter the amount of LP for the lock, like Aura Finance

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by garethfuller** [comment]
We decided against this because you can unstake at any time. You can also get around this limitation buy LPing, staking, then LPing again. Is there a particular reason you'd like to have some staked and unstaked LP tokens at the same time?

**Comment by khbw** [comment]
For example, I add liquidity to get bb-e-usd lp token, 80% of lp token is directly locked in bb-e-usd guage, and after a while, I will pair 20% lp with wstETH to continue adding liquidity. Of course, I also have other ways to bypass this limit, but why set this limit for users? In addition, I am used to reserve a small part of the balance in the wallet for any token, so as to save gas when adding it next time.

**Comment by garethfuller** [comment]
This came up in a design review again. We are still in favour of keeping the UI as simple as possible here and will not be making this possible.
