### ISSUE TITLE
Popular tokens filter

### ISSUE THREAD

**Issue by gmbronco** [balancer/frontend-v2#3102]
**Describe the bug**
1. After selecting and deselecting a token several times, the "popular" token selector was replaced by the "wallet" selector unexpectedly.
2. (nice to have) While a filtered token list is loading, removing a selected token is blocked. Would be nicer to be able to clear the token mid request to have a snappier UX feel.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [https://app.balancer.fi/](https://app.balancer.fi/)
3. Click on a token from "Popular" list
4. Repeat a couple of times with different tokens 
5. See "Popular" getting replaced by "Wallet"

**Expected behaviour**
The "popular" token selector remains visible and functional.

**Screenshots**

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Brave
- Version: 1.49.128

**Additional context**

**Comment by garethfuller** [comment]
We no longer have the popular token section so I don't think this issue is relevant anymore.
