### ISSUE TITLE
Error `eth_signTypedData_v4 is not supported` in Zodiac Pilot

### ISSUE THREAD

**Issue by jfschwarz** [balancer/frontend-v2#3208]
**Describe the bug**
We are maintaining [Zodiac Pilot](https://pilot.gnosisguild.org), an injected wallet (EIP-1193) that does not support `eth_signTypedData_v4`. The Balancer UI makes the assumption that every injected wallet supports this RPC method. Thus we are currently unable to use Zodiac Pilot for providing liquidity to pools using the batch relayer.

**To Reproduce**

1. Install Zodiac Pilot Chrome extension
2. Open https://pilot.gnosisguild.org/#https%3A%2F%2Fapp.balancer.fi%2F%23%2Fgnosis-chain%2Fpool%2F0xf48f01dcb2cbb3ee1f6aab0e742c2d3941039d56000200000000000000000012
3. Connect wallet (select MetaMask) and go to 'Add liquidity'
4. Enter amounts and click 'Preview'
5. Click 'Approve Batch Relayer'
6. See error `eth_signTypedData_v4 is not supported`

**Expected behavior**
It should use the transaction approval flow rather than the signature approval one.

**Screenshots**
![image](https://user-images.githubusercontent.com/524089/233603916-ac8dba63-36e4-4a33-9392-33b5019000e1.png)

**Additional context**
Zodiac Pilot is the tool being used by Karpatkey to manage the treasury of Balancer. This issue blocks their execution team to efficiently interact with pools using the batch relayer. cc @sgzerbo

**Proposed solution**
I see two options this could be fixed in [useRelayerApproval.ts](https://github.com/balancer/frontend-v2/blob/develop/src/composables/approvals/useRelayerApproval.ts):
- generic probe via an invalid (empty params) test call to `eth_signTypedData_v4`. If you get an error response with the message "Method eth_signTypedData_v4 is not supported" then you know it's not supported.
- Zodiac Pilot specific fix: check if the app is running in a Zodiac Pilot context via `window.ethereum['isZodiac Pilot']`

**Comment by garethfuller** [comment]
@jfschwarz instead of a specific fix, we've added a user setting where you can turn off the use of signatures (see screenshot). I hope this helps, if not please let me know.
<img width="452" alt="Screenshot 2023-05-08 at 16 03 01" src="https://user-images.githubusercontent.com/2406506/236863360-5d35699d-9e98-472f-aef3-bde8afbd765d.png">
