### ISSUE TITLE
Host Balancer frontend on IPFS and Arweave

### ISSUE THREAD

**Issue by invinciblemax** [balancer/frontend-v2#3308]
**Description**

Hi Balancer team, nice to meet you! Max from 4EVERLAND. 

https://www.4everland.org
4EVERLAND is a Web3 cloud computing platform, provides one-stop solution for projects and users host the front-end on top of IPFS, Arweave and Dfinity.

**Benefits of decentralized frontend**
Decentralized website brings many advantages, including censorship resistance, immutability, and multiple backups, which can effectively help projects avoid problems caused by centralized institutions or servers.

We hope to partner with Balancer and assist you in swiftly and easily hosting your frontend on decentralized storage through our services. Here are some of the distinctive features and advantages of 4EVERLAND, in the hopes of assisting you in gaining a better understanding of our services.

**Multiple deployment options and hosting layers**

4EVERLAND supports CI/CD, CLI and even direct deployment via IPFS CID, with a variety of deployment options to help you host your front-end on decentralized storage according to your actual needs. 
And 4EVERLAND is the only platform provide IPFS, Arweave and Dfinity hosting solution in one.

**Deploy hook and IPNS**

The front-end hosted on decentralized storage via 4EVERLAND will be automatically updated with the Github updates, meanwhile 4EVERLAND supports IPNS, the features will greatly reduce the maintenance costs.

**DNS, ENS, SNS…**

4EVERLAND supports DNS and a large number of decentralized domains bindings, including ENS or Bonfida. With the public gateway, for instance: eth.limo, your can enjoy the permissionless gateway as your DWeb’s domain.

**Global Acceleration**

4EVERLAND has widely distributed gateways and IPFS nodes around the world. 4EVERLAND provides global acceleration for hosted websites regardless of IPFS protocol or HTTP protocol, and because of 4EVERLAND's widely distributed IPFS nodes, our performance on the IPFS network is greatly improved. You can check https://pineapple.fyi/, the data means the 1st provider finish store the data on IPFS, we hit 99% 1st among all Snapshot IPFS providers (Pinata, Fleek, Infura, Web3storage) 
https://twitter.com/SnapshotLabs/status/1567432510111629312

**Free to use**

For hosting service, **the free resource (6GB IPFS, 100MB Arweave, 100GB bandwidth/month) we provide for each user is enough for vast majority of projects.** Of course we are glad to discuss with Balancer a exclusive plan to advance the partnership.

Besides our hosting solution, we provide IPFS, Arweave storage and gateway services as well and would love to provide the solid solution for Balancer.

You can learn more about 4EVERLAND via:
https://www.notion.so/4EVERLAND-in-ONE-6ab6ff9936a14a1bbac6e0b4f989d7ad

**Our team would love to answer any questions and we could submit a PR to facilitate the integration.**

Looking forward to your response and excited for stepping into collaboration.

**Comment by garethfuller** [comment]
We are not looking to host the frontend on IPFS at this time.
