### ISSUE TITLE
update veBAL page to somehow expose supply info and contract address.

### ISSUE THREAD

**Issue by Tritium-VLK** [balancer/frontend-v2#3954]
**Is your feature request related to a problem? Please describe.**
Update veBAL page to show the current total and voting supplies of veBAL and somewhere expose/link to the contract address.

**Describe the solution you'd like**
It's really hard to find the veBAL contract and figure out your vote weight/etc right now.  This would make veBAL less mysterious.  Spent 10 mins trying to figure it all out myself today.

**Describe alternatives you've considered**
Have also asked the Defilytica crew to expose this data.

**Comment by garethfuller** [comment]
We'll take a look at including this in the veBAL redesign that's going on.

**Comment by garethfuller** [comment]
Closing, but this is being considered.
