### ISSUE TITLE
Bug: Removing Liquidity from pool gives multiple errors: BAL#505 BAL#306 

### ISSUE THREAD

**Issue by sambacha** [balancer/frontend-v2#4224]
**Describe the bug**
Go to balancer page
withdraw from 50/50 proportionally from FOLD/WETH pool

get these errors

**Comment by sambacha** [comment]
Here are the raw logs of the errors 

yes I built site locally to see if regression i went back 5 releases 

[app.balancer.fi-1695374432168.log](https://github.com/balancer/frontend-v2/files/12699180/app.balancer.fi-1695374432168.log)
[localhost-1695374407773.log](https://github.com/balancer/frontend-v2/files/12699181/localhost-1695374407773.log)

**Comment by sambacha** [comment]
hello @alter-eggo or @Tritium-VLK 

this issue still persists

**Comment by garethfuller** [comment]
BAL 505 is returned when slippage is too low. Please try upping slippage. We will be adding better error messages to account for this issue.
