### ISSUE TITLE
Remove warning on wjAURA-WETH pool

### ISSUE THREAD

**Issue by 0x-ultra** [balancer/frontend-v2#4417]
<img width="845" alt="image" src="https://github.com/balancer/frontend-v2/assets/77009494/3c52ce69-80d7-4e7e-a403-accb3cc7f57a">

The warning above is currently displayed on the wjAURA-WETH pool on balancer and liquidity provision is disabled.  
  
As discussed with @Tritium-VLK - this appears to be happening as the rate provider for this pool is flagged as working incorrectly.  
  
It was agreed upon at the onset of this strategy, with both the Balancer and Aura teams' approval, that the pool would be created as a no-fee pool. However, due to internal miscommunication, the pool was initially set up with a working rate provider.  
  
When we identified the wrong set up, the situation was discussed again amongst our two teams and a quick solution was determined wherein stopping any update to the rate provider was the best way forward. The rate provided has been constant for a few months now.  
  
The pool has been operating without any issues since inception and currently has 1.6M dollars in TVL.  
  
We would like to work with Balancer on a long-term solution that aligns to a more standard architecture for pools of this nature, but would appreciate the FE team providing an override so that UX doesn't suffer in the interim.  
  
### Links
[wjAURA-WETH pool](https://app.balancer.fi/#/ethereum/pool/0x68e3266c9c8bbd44ad9dca5afbfe629022aee9fe000200000000000000000512)

[BIP-250](https://forum.balancer.fi/t/bip-250-enable-jaura-eth-80-20-gauge-w-10-emissions-cap-ethereum/4597)

[Rate provider](https://etherscan.io/address/0x3556F710c165090AAE9f98Eb62F5b04ADeF7Eaea#readContract)

**Comment by Tritium-VLK** [comment]
I confirm that we had this conversation and are working on a long term solution.  In the meantime, this pool has been working fine for a while and I agree it would be good to allow users the ability to interact.
