### ISSUE TITLE
Bug: when creating a new pool, if the creation process is interrupted user is unable to complete the creation process

### ISSUE THREAD

**Issue by sambacha** [balancer/frontend-v2#4526]
**Describe the bug**
1. Create a new weighted pool
	- 80%
	- 20%
2. Set pool fees
3. Set initial Liquidity  
4. Confirm Pool Creation

**To Reproduce**

At step 3, exit the browser entirely.
Re-login with a new browser instance, and try to fund the pool liquidity ('Join Pool')

We are unable to 'Join Pool' due to 
```
MetaMask - RPC Error: execution reverted: BAL#103 
```

This is because the user is brought to the `CONFIRMATION` page for funding the pool, the user instead should be sent back to the 'Set Initial Liquidity page' to recalculate the weight amounts for the respective tokens, as the state is not retained from the first calculation.

**Expected behavior**

Have the user re-calculate the liquidity amounts and put them back on the 'Set initial liquidity page'

**Comment by sambacha** [comment]
Attached are the log output of the errors and a screenshot of the page that the user is brought back to upon trying to resume pool creation

[app.balancer.fi-1699292984770.zip](https://github.com/balancer/frontend-v2/files/13270848/app.balancer.fi-1699292984770.zip)
<img width="1620" alt="Screenshot 2023-11-06 at 9 52 18 AM" src="https://github.com/balancer/frontend-v2/assets/32783916/19393ab7-f077-49e3-93c4-9f299d3c36d1">

**Comment by garethfuller** [comment]
Thanks for providing the details here @sambacha, we'll try to fix asap.

**Comment by garethfuller** [comment]
We've started to retire this app in favour of [https://balancer.fi](https://balancer.fi) so closing this.
