### ISSUE TITLE
ezETH APR on Arbitrum

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/frontend-v2#5419]
ezETH is live on Arbitrum in this pool and showing their APR on the UI is helpful for LPs to know their full return. 
Pool: https://app.balancer.fi/#/arbitrum/pool/0xb61371ab661b1acec81c699854d2f911070c059e000000000000000000000516
Token: https://arbiscan.io/address/0x2416092f143378750bb29b79ed961ab195cceea5
API Endpoint: https://app.renzoprotocol.com/api/apr

**Comment by gmbronco** [comment]
done
