### ISSUE TITLE
2CLP Pools on Arbtrium not votable on veBAL Screen

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/frontend-v2#5556]
aUSDC/USDC https://arbiscan.io/address/0xcA8ECD05A289B1FBc2E0eAEC07360c4BFec07B61 gauge:
- child chain gauge on Arbitrum: 0xe39fEEB09C4dDE420eAAADd066F949ab84c94bb8 (https://arbiscan.io/address/0xe39fEEB09C4dDE420eAAADd066F949ab84c94bb8)
- root gauge on Ethereum: 0x75BA7F8733c154302cbE2e19fe3ec417E0679833 (https://etherscan.io/address/0x75BA7F8733c154302cbE2e19fe3ec417E0679833)

aUSDT/USDT https://arbiscan.io/address/0x14ABD18d1FA335E9F630a658a2799B33208763Fa gauge:
- child chain gauge on Arbitrum: 0x1C8D981BBc56B7C65289FE34d7FF692ABDe9c8D5 (https://arbiscan.io/address/0x1C8D981BBc56B7C65289FE34d7FF692ABDe9c8D5)
- root gauge on Ethereum: 0xF937BF168B33D8D10d555e9a039Ec1B8e4c543d1 (https://etherscan.io/address/0xF937BF168B33D8D10d555e9a039Ec1B8e4c543d1)

(forum post for reference: https://forum.balancer.fi/t/bip-576-enable-ausdc-usdc-and-ausdt-usdt-gauges-arbitrum/5660)

**Comment by franzns** [comment]
This is fixed now for the vebal screen, that was an API issue. 

It does show unknown pool type on the frontend though: https://app.balancer.fi/#/arbitrum/pool/0xca8ecd05a289b1fbc2e0eaec07360c4bfec07b6100020000000000000000051d 

Some context: the pool was created with a factory that was not tracked by the subgraph (new factory). It was added to the subgraph last week.
